services:
  postgres:
    image: postgres:16
    container_name: video-delivery-postgres
    environment:
      POSTGRES_USER: delivery
      POSTGRES_PASSWORD: delivery
      POSTGRES_DB: video_delivery_analytics
    ports:
      - "55434:5432"
    volumes:
      - video_delivery_pgdata:/var/lib/postgresql/data

volumes:
  video_delivery_pgdata:
